version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: opencart-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencartpass
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    image: webdevops/php-apache:7.4
    container_name: opencart-web
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 20M
      PHP_POST_MAX_SIZE: 20M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_DISPLAY_ERRORS: 0
    ports:
      - "80:80"

volumes:
  db_data:
  